services:
  ironlink:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ironlink
    restart: unless-stopped
    ports:
      - "80:80"
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://ironlink_user:ironlink_password@localhost:5432/ironlink
    # network_mode: host


volumes:
  postgres_data:
    driver: local

