CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Set timezone
SET timezone = 'UTC';

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE ironlink TO ironlink_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ironlink_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ironlink_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ironlink_user;

-- Set default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ironlink_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ironlink_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ironlink_user; 